# ===================================================================
# Spring Boot configuration for the "dev" profile.
# ===================================================================
spring:
  cloud:
    azure:
      storage:
        account-name: ${AZURE_STORAGE_ACCOUNT_NAME} # environment variable with a default value
        account-key: ${AZURE_STORAGE_ACCOUNT_KEY} # environment variable with a default value
  servlet:
    multipart:
      enabled: true
      max-file-size: 2MB
      max-request-size: 10MB
  devtools:
    restart:
      enabled: true
      additional-exclude: static/**
    livereload:
      enabled: false # we use Webpack dev server + BrowserSync for livereload
  jackson:
    serialization:
      indent-output: true
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://103.188.82.34:3306/ftms?useLegacyDatetimeCode=false&serverTimezone=UTC&useJvmCharsetConverters=true&trustServerCertificate=true
    username: root
    password: 0912481511
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  liquibase:
    contexts: dev, faker
  mail:
    host: smtp.gmail.com
    port: 587
    username: academyfsoft@gmail.com
    password: hmjc vetf gopy brdj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  messages:
    cache-duration: PT1S # 1 second, see the ISO 8601 standard
  thymeleaf:
    cache: false

server:
  port: 8080

jhipster:
  cors:
    allowed-origins: 'http://localhost:8100,https://localhost:8100,http://localhost:9000,https://localhost:9000,http://localhost:9060,https://localhost:9060'
    allowed-origin-patterns: 'https://*.githubpreview.dev'
    allowed-methods: '*'
    allowed-headers: '*'
    exposed-headers: 'Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params'
    allow-credentials: true
    max-age: 1800
#  security:
#    authentication:
#      jwt:
#        base64-secret: MzljYjY4OWUxYjljYmJjMjdkYzMxNjQ3YjJjMmVmMTg5ODE2MTgwNDBhNWI3MTcxMmE5ZDgyNTI5MTdiNGMwNzc3ZDc2OGJjZTkyNWU0MDc1MGQwZDgyZDA3MzE5Mjg0OWEzMGZiYWE3OTE5YTk1NDE5ZmM3YzYwNDFhMWUyMTI=
#        token-validity-in-seconds: 86400
#        token-validity-in-seconds-for-remember-me: 2592000
  mail:
    base-url: http://127.0.0.1:8080
  logging:
    use-json-format: false
    logstash:
      enabled: false
      host: localhost
      port: 5000
      ring-buffer-size: 512

application:
  file-upload:
    upload-dir: 'C:/Users/saltluxpc/Desktop/uploads'
  cron:
    one-minute: '0 * * * * ?'
    a-week: '0 0 * * * SUN'
    a-day: '0 0 0 * * ?'
springdoc:
  swagger-ui:
    path: /swagger-ui.html

## DataSource configuration
#  spring.datasource.url=jdbc:mysql://localhost:3306/ftms
#  spring.datasource.username=root
#  spring.datasource.password=12345678
#  spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#
#  ra.jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
#  ra.jwt.expiration=3600000
#
#
#  #logging.level.org.springframework=DEBUG
#
#  # JPA configuration
#  spring.jpa.hibernate.ddl-auto=update
#  spring.jpa.show-sql=true
#  spring.sql.init.mode=always
#  spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
#
#
#  # HikariCP connection pool configuration
#  spring.datasource.hikari.connection-timeout=20000
#  spring.datasource.hikari.minimum-idle=10
#  spring.datasource.hikari.maximum-pool-size=10
#  spring.datasource.hikari.idle-timeout=300000
#  spring.datasource.hikari.max-lifetime=1800000
#
#  # Email configuration
#  spring.mail.host=smtp.gmail.com
#  spring.mail.port=587
#  spring.mail.username=nganqhe163725@fpt.edu.vn
#  spring.mail.password=ipwo ngmj tcee wlys
#  spring.mail.properties.mail.smtp.auth=true
#  spring.mail.properties.mail.smtp.starttls.enable=true
#  spring.mail.properties.mail.smtp.starttls.required=true